#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

# USER-TODO: specify the class(es) implemented in this module
MODULE_CLASSES=hwpq-decoder

# USER-TODO: set file-names
SRC_FILES = hwpq-decoder.c pq.h opal-bitlib.h gab_helper.h

MODULE_CFLAGS =

EXTRA_VPATH=

include $(MODULE_MAKEFILE)
