#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = tarfile

SRC_FILES= tarfile.c

include $(MODULE_MAKEFILE)
